### PR TITLE
updated code & example to be compatible with swift 4.2

### PR DESCRIPTION
**Pull request by michakfromparis**

### CODE REVIEW

**Comment by yannickl** [comment]
Thank you for your help. They are still some errors with the test project but I'm going to fix that.

**Comment by michakfromparis** [comment]
Yes, I noticed. I meant to fix that and then was dragged to dinner. I might have some time for it in a few hours.

**Comment by yannickl** [comment]
I've already fixed the issue, so you don't have to worry about it. ;)

**Comment by michakfromparis** [comment]
Great! Thanks!

**Pull request merged**
